name: pre-commit
description: run pre-commit

runs:
  using: composite
  steps:
    - name: Get Current Python Version
      shell: python
      id: py
      run: |
        import os
        import sys
        import hashlib

        v = hashlib.sha3_224(sys.version.encode()).hexdigest()

        with open(os.environ["GITHUB_OUTPUT"], 'a+', encoding="utf-8") as f:
            env = f.write(f"\nPY={v}\n")

    - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
      id: cache
      with:
        path: ~/.cache/pre-commit
        key: pre-commit-3-${{ steps.py.outputs.PY }}-${{ hashFiles('.pre-commit-config.yaml') }}
        restore-keys: |
          pre-commit-3-${{ steps.py.outputs.PY }}-

    - run: pre-commit run --all-files --show-diff-on-failure --color=always
      shell: bash

    - name: Run this action with only post
      if: steps.cache.outputs.cache-hit != 'true'
      uses: gacts/run-and-post-run@d803f6920adc9a47eeac4cb6c93dbc2e2890c684 # v1
      with:
        post: pre-commit gc
