inputs:
  cache-namespace:
    description: "cache-namespace"
    required: false
    default: "build"

name: "Setup Golang"
description: "setup golang env"
runs:
  using: "composite"
  steps:
    - run: echo "GOTOOLCHAIN=local" >> $GITHUB_ENV
      shell: bash

    - id: gomod
      uses: Arthur1/parse-gomod-action@f8b23275f54183926505e6e09703b01ba9c115e3 # v0.1.0

    - name: Install Go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
      with:
        go-version: ${{ steps.gomod.outputs.toolchain-go-version || steps.gomod.outputs.go }}
        cache: false

    - name: Go Build Cache
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg
        key: go-cache-${{ hashFiles('go.mod') }}-${{ hashFiles('go.sum') }}-${{ inputs.cache-namespace }}
        restore-keys: |
          go-cache-${{ hashFiles('go.mod') }}-${{ hashFiles('go.sum') }}-
          go-cache-${{ hashFiles('go.mod') }}-

    - run: go get ./...
      shell: bash
