inputs:
  cache-namespace:
    description: "cache-namespace"
    required: false
    default: "build"

name: "Setup Golang"
description: "setup golang env"
runs:
  using: "composite"
  steps:
    - name: Install Go
      uses: actions/setup-go@v6
      with:
        go-version-file: go.mod
        cache: false

    - name: Go Build Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg
        key: go-cache-${{ hashFiles('go.mod') }}-${{ hashFiles('go.sum') }}-${{ inputs.cache-namespace }}
        restore-keys: |
          go-cache-${{ hashFiles('go.mod') }}-${{ hashFiles('go.sum') }}-
          go-cache-${{ hashFiles('go.mod') }}-

    - run: go get ./...
      shell: bash
