inputs:
  cache-namespace:
    description: "cache-namespace"
    required: false
    default: "build"

name: "Setup Golang"
description: "setup golang env"
runs:
  using: "composite"
  steps:
    - run: echo "GOTOOLCHAIN=local" >> $GITHUB_ENV
      shell: bash

    - id: gomod
      uses: Arthur1/parse-gomod-action@v0.1.0

    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ steps.gomod.outputs.toolchain-go-version || steps.gomod.outputs.go }}
        cache: false

    - name: Go Cache
      uses: actions/cache@v4
      if: ${{ inputs.cache-namespace == ''}}
      with:
        path: ~/go/pkg
        key: go-cache-${{ hashFiles('go.mod') }}-${{ hashFiles('go.sum') }}-
        restore-keys: |
          go-cache-${{ hashFiles('go.mod') }}-

    - name: Go Build Cache (${{ inputs.cache-namespace }})
      uses: actions/cache@v4
      if: ${{ inputs.cache-namespace != ''}}
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg
        key: go-cache-${{ hashFiles('go.mod') }}-${{ hashFiles('go.sum') }}-${{ inputs.cache-namespace }}
        restore-keys: |
          go-cache-${{ hashFiles('go.mod') }}-${{ hashFiles('go.sum') }}-
          go-cache-${{ hashFiles('go.mod') }}-

    - run: go get ./...
      shell: bash
