name: prek
description: run prek (pre-commit replacement)

runs:
  using: composite
  steps:
    - name: Check runner
      shell: bash
      run: |
        set -euo pipefail
        if [[ "${RUNNER_OS:-}" != "Linux" || "${RUNNER_ARCH:-}" != "X64" ]]; then
          echo "This action only supports Linux X64 (got ${RUNNER_OS:-unknown}/${RUNNER_ARCH:-unknown})" >&2
          exit 1
        fi

    - name: Install prek
      shell: bash
      run: |
        set -euo pipefail
        echo "$HOME/.local/bin" >> "$GITHUB_PATH"
        curl --proto '=https' --tlsv1.2 -LsSf https://github.com/j178/prek/releases/latest/download/prek-installer.sh | sh
        command -v prek
        prek --version

    - uses: actions/cache@v5
      with:
        path: ~/.cache/prek
        key: prek-1-${{ hashFiles('.pre-commit-config.yaml') }}

    - name: Run prek
      shell: bash
      run: prek run --all-files --show-diff-on-failure --color=always
